"""add threshold_cascade to user

Revision ID: 1ab1b4e527c3
Revises: bfa05c7d8635
Create Date: 2026-05-17 17:13:48.257334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab1b4e527c3'
down_revision: Union[str, Sequence[str], None] = 'bfa05c7d8635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('threshold_cascade', sa.Float(), nullable=False, server_default='5000.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'threshold_cascade')
    # ### end Alembic commands ###
