"""add_new_filed_for_finance_system

Revision ID: 2afcea59f9aa
Revises: b11682bb8446
Create Date: 2026-06-27 17:37:54.532458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afcea59f9aa'
down_revision: Union[str, Sequence[str], None] = 'b11682bb8446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payload', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('is_reminder_sent', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('last_renewal_attempt', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('auto_renewal', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_column('users', 'threshold_vol_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('threshold_vol_pct', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('users', 'auto_renewal')
    op.drop_column('users', 'last_renewal_attempt')
    op.drop_column('invoices', 'is_reminder_sent')
    op.drop_column('invoices', 'payload')
    # ### end Alembic commands ###
