"""add_coin_fundamentals

Revision ID: 384729097e60
Revises: edd3e25246fa
Create Date: 2026-06-25 16:17:37.901664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384729097e60'
down_revision: Union[str, Sequence[str], None] = 'edd3e25246fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_fundamentals',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('circulating_supply', sa.Float(), nullable=False),
    sa.Column('cg_id', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin_fundamentals')
    # ### end Alembic commands ###
