"""add_stage2_settings

Revision ID: 5c8272312191
Revises: 1ab1b4e527c3
Create Date: 2026-05-26 13:25:12.741323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8272312191'
down_revision: Union[str, Sequence[str], None] = '1ab1b4e527c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alert_oi', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('threshold_oi_percent', sa.Float(), nullable=False, server_default='5.0'))
    op.add_column('users', sa.Column('threshold_oi_value', sa.Float(), nullable=False, server_default='500000.0'))
    op.add_column('users', sa.Column('alert_cvd', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('alert_rsi', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
