"""full init DB

Revision ID: 719554d6009f
Revises: 
Create Date: 2026-06-02 17:44:28.044368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719554d6009f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidations_symbol'), 'liquidations', ['symbol'], unique=False)
    op.create_index(op.f('ix_liquidations_timestamp'), 'liquidations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_liquidations_value'), 'liquidations', ['value'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('is_trial_used', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('threshold_cascade', sa.Float(), nullable=False),
    sa.Column('alert_cascade', sa.Boolean(), nullable=False),
    sa.Column('alert_volume', sa.Boolean(), nullable=False),
    sa.Column('alert_squeeze', sa.Boolean(), nullable=False),
    sa.Column('alert_oi', sa.Boolean(), nullable=False),
    sa.Column('threshold_oi_percent', sa.Float(), nullable=False),
    sa.Column('threshold_oi_value', sa.Float(), nullable=False),
    sa.Column('alert_cvd', sa.Boolean(), nullable=False),
    sa.Column('alert_rsi', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_liquidations_value'), table_name='liquidations')
    op.drop_index(op.f('ix_liquidations_timestamp'), table_name='liquidations')
    op.drop_index(op.f('ix_liquidations_symbol'), table_name='liquidations')
    op.drop_table('liquidations')
    # ### end Alembic commands ###
