"""add_mcap_threshold_fields

Revision ID: b11682bb8446
Revises: 384729097e60
Create Date: 2026-06-25 19:22:54.210371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11682bb8446'
down_revision: Union[str, Sequence[str], None] = '384729097e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_settings', sa.Column('threshold_mode', sa.String(length=20), nullable=False, server_default='usd'))
    op.add_column('channel_settings', sa.Column('threshold_mcap_pct', sa.Float(), nullable=False, server_default='0.005'))
    op.add_column('channel_settings', sa.Column('threshold_mcap_usd_min', sa.Float(), nullable=False, server_default='1000.0'))
    op.add_column('channel_settings', sa.Column('threshold_cascade_mcap_pct', sa.Float(), nullable=False, server_default='0.01'))
    op.add_column('channel_settings', sa.Column('threshold_cascade_mcap_usd_min', sa.Float(), nullable=False, server_default='5000.0'))
    op.add_column('users', sa.Column('threshold_mode', sa.String(length=20), nullable=False, server_default='usd'))
    op.add_column('users', sa.Column('threshold_mcap_pct', sa.Float(), nullable=False, server_default='0.005'))
    op.add_column('users', sa.Column('threshold_mcap_usd_min', sa.Float(), nullable=False, server_default='1000.0'))
    op.add_column('users', sa.Column('threshold_cascade_mcap_pct', sa.Float(), nullable=False, server_default='0.01'))
    op.add_column('users', sa.Column('threshold_cascade_mcap_usd_min', sa.Float(), nullable=False, server_default='5000.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'threshold_cascade_mcap_usd_min')
    op.drop_column('users', 'threshold_cascade_mcap_pct')
    op.drop_column('users', 'threshold_mcap_usd_min')
    op.drop_column('users', 'threshold_mcap_pct')
    op.drop_column('users', 'threshold_mode')
    op.drop_column('channel_settings', 'threshold_cascade_mcap_usd_min')
    op.drop_column('channel_settings', 'threshold_cascade_mcap_pct')
    op.drop_column('channel_settings', 'threshold_mcap_usd_min')
    op.drop_column('channel_settings', 'threshold_mcap_pct')
    op.drop_column('channel_settings', 'threshold_mode')
    # ### end Alembic commands ###
