"""add table channel settings

Revision ID: bd8e3707866f
Revises: da90e1c4f718
Create Date: 2026-06-05 19:07:09.023696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8e3707866f'
down_revision: Union[str, Sequence[str], None] = 'da90e1c4f718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('threshold_cascade', sa.Float(), nullable=False),
    sa.Column('alert_cascade', sa.Boolean(), nullable=False),
    sa.Column('alert_volume', sa.Boolean(), nullable=False),
    sa.Column('alert_squeeze', sa.Boolean(), nullable=False),
    sa.Column('alert_oi', sa.Boolean(), nullable=False),
    sa.Column('threshold_oi_percent', sa.Float(), nullable=False),
    sa.Column('threshold_oi_value', sa.Float(), nullable=False),
    sa.Column('alert_cvd', sa.Boolean(), nullable=False),
    sa.Column('alert_rsi', sa.Boolean(), nullable=False),
    sa.Column('dashboard_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_summary_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_settings')
    # ### end Alembic commands ###
