"""add last_expiry_warning_at to user

Revision ID: c15c32e4d47c
Revises: 2afcea59f9aa
Create Date: 2026-06-27 19:38:06.616729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15c32e4d47c'
down_revision: Union[str, Sequence[str], None] = '2afcea59f9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_expiry_warning_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_expiry_warning_at')
    # ### end Alembic commands ###
