"""added_alert_toggles

Revision ID: cce463e71b0b
Revises: 34b4f6237ab6
Create Date: 2026-05-15 19:44:37.736018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce463e71b0b'
down_revision: Union[str, Sequence[str], None] = '34b4f6237ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alert_cascade', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('alert_volume', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('alert_squeeze', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alert_squeeze')
    op.drop_column('users', 'alert_volume')
    op.drop_column('users', 'alert_cascade')
    # ### end Alembic commands ###
