"""remove tariff_days from table invoices

Revision ID: da089d5c8bd5
Revises: ff086549bb92
Create Date: 2026-06-13 10:43:19.436113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da089d5c8bd5'
down_revision: Union[str, Sequence[str], None] = 'ff086549bb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'crypto_pay_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_crypto_pay_id'), table_name='invoices')
    op.create_unique_constraint(None, 'invoices', ['crypto_pay_id'])
    op.drop_column('invoices', 'tariff_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('tariff_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_crypto_pay_id'), 'invoices', ['crypto_pay_id'], unique=True)
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.alter_column('invoices', 'crypto_pay_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
