"""add_direction_filters

Revision ID: edd3e25246fa
Revises: da089d5c8bd5
Create Date: 2026-06-25 09:50:18.477739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd3e25246fa'
down_revision: Union[str, Sequence[str], None] = 'da089d5c8bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_settings', sa.Column('alert_longs', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('channel_settings', sa.Column('alert_shorts', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('channel_settings', sa.Column('threshold_vol_pct', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('users', sa.Column('alert_longs', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('alert_shorts', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('threshold_vol_pct', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'threshold_vol_pct')
    op.drop_column('users', 'alert_shorts')
    op.drop_column('users', 'alert_longs')
    op.drop_column('channel_settings', 'threshold_vol_pct')
    op.drop_column('channel_settings', 'alert_shorts')
    op.drop_column('channel_settings', 'alert_longs')
    # ### end Alembic commands ###
